---
- name: Buscar archivos con extensiones específicas en todos los discos y guardar reporte por equipo
  hosts: all
  gather_facts: yes
  become: yes

  tasks:

    - name: Generar archivo CSV con resultados
      win_shell: |
        $jsonPath = "C:\\temp\\valid_files2.json"
        $data = Get-Content -Path $jsonPath | ConvertFrom-Json
        $hostname = $env:COMPUTERNAME
        $header = "Equipo,Path,Size (bytes),CreationTime,LastWriteTime,LastAccessTime"
        $csvData = @()
        foreach ($file in $data) {
          $creationTime = if ($file.CreationTime) { $file.CreationTime } else { "-" }
          $lastWriteTime = if ($file.LastWriteTime) { $file.LastWriteTime } else { "-" }
          $lastAccessTime = if ($file.LastAccessTime) { $file.LastAccessTime } else { "-" }
          $csvData += "$hostname,`"$($file.FullName)`",$($file.Length),$creationTime,$lastWriteTime,$lastAccessTime"
        }
        $csvPath = "C:\\temp\\${hostname}_file_report3.csv"
        $header | Out-File -FilePath $csvPath -Encoding UTF8
        $csvData | Out-File -FilePath $csvPath -Append -Encoding UTF8
        Write-Output "CSV generado en $csvPath"
      args:
        executable: powershell

    - name: Registrar mensaje de éxito
      debug:
        msg: "El archivo CSV ha sido generado con el nombre del equipo en C:\\temp\\<equipo>_file_report.csv"
