---
- name: Buscar archivos con extensiones específicas en todos los discos y guardar reporte por equipo
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Obtener las unidades disponibles en el equipo
      win_shell: |
        Get-PSDrive -PSProvider FileSystem | Where-Object { $_.Free -ne $null } | Select-Object -ExpandProperty Name
      register: drives

    - name: Construir la lista de rutas para buscar
      set_fact:
        search_paths: "{{ drives.stdout_lines | map('regex_replace', '^(.*)$', '\\1:\\\\') | list }}"

    - name: Verificar las rutas generadas
      debug:
        var: search_paths

    - name: Buscar archivos con extensiones .pdf, .hsc y .shp en todas las unidades
      win_find:
        paths: "{{ search_paths }}"
        patterns:
          - "*.shp"
          - "*.gdb"
          - "*.hsc"
          - "*.pet"

        recurse: yes
      register: found_files

    - name: Filtrar archivos excluyendo ciertos directorios
      set_fact:
        filtered_files: >
          {{ found_files.files | selectattr('path', 'search', '^(?!C:\\\\Windows|C:\\\\Program Files|C:\\\\Program Files \\(x86\\)|C:\\\\$Recycle.Bin).*') | list }}

    - name: Recolectar información y formatear resultados en CSV
      set_fact:
        csv_data: >
          Nombre del Archivo,Ruta,Tamaño (bytes)
          {{ filtered_files | map('extract', ['name', 'path', 'size']) | map('join', ',') | join('\n') }}

    - name: Agregar encabezado y nombre del equipo al archivo CSV
      set_fact:
        output_csv: >
          Equipo: {{ ansible_hostname }}
          {{ csv_data }}

    - name: Guardar información en un archivo CSV con el nombre del equipo
      win_copy:
        content: "{{ output_csv }}"
        dest: "C:\\Users\\Public\\{{ ansible_hostname }}_unidades.txt"
