---
- name: Buscar archivos con extensiones específicas en todos los discos y guardar reporte por equipo
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Crear la carpeta C:\temp si no existe
      win_file:
        path: C:\temp
        state: directory

    - name: Obtener las unidades disponibles en el equipo
      win_shell: |
        Get-PSDrive -PSProvider FileSystem | Where-Object { $_.Free -ne $null } | Select-Object -ExpandProperty Name
      register: drives

    - name: Construir la lista de rutas para buscar
      set_fact:
        search_paths: "{{ drives.stdout_lines | map('regex_replace', '^(.*)$', '\\1:\\\\') | list }}"

    - name: Validar que existan rutas de búsqueda
      fail:
        msg: "No se encontraron unidades disponibles para buscar archivos."
      when: search_paths | length == 0

    - name: Verificar las rutas generadas
      debug:
        var: search_paths

    - name: Buscar archivos con extensiones específicas en todas las unidades
      win_find:
        paths: "{{ search_paths }}"
        patterns:temp
          - "*.shp"
          - "*.gdb"
          - "*.hsc"
          - "*.pet"
        recurse: yes
      register: found_files

    - name: Filtrar archivos excluyendo ciertos directorios
      set_fact:
        filtered_files: >
          {{ found_files.files | selectattr('path', 'search', '^(?!C:\\\\Windows|C:\\\\Program Files|C:\\\\Program Files \\(x86\\)|C:\\\\$Recycle.Bin).*') | list }}

    - name: Recolectar información y formatear resultados en CSV
      set_fact:
        csv_data: >
          Nombre del Archivo,Ruta,Tamaño (bytes)
          {{ filtered_files | map('extract', ['name', 'path', 'size']) | map('join', ',') | join('\n') }}

    - name: Guardar información en un archivo CSV con el nombre del equipo
      win_copy:
        content: "{{ csv_data }}"
        dest: "C:\\temp\\{{ ansible_hostname }}_archivos.csv"

    - name: Mostrar mensaje de finalización
      debug:
        msg: "La información se ha guardado en C:\\temp\\{{ ansible_hostname }}_archivos.csv"
