- name: Ejecutar archivo .exe
  hosts: all
  gather_facts: no
  become: yes

  vars:
    #ruta_archivo_exe: 'C:\Users\Public\MFA\LogInAnd\Replicar.exe'
    ruta_archivo_exe: 'C:\Windows\System32\ruta_archivo_exe:'

  tasks:
    - name: Ejecutar archivo .exe
      win_command: "{{ ruta_archivo_exe }}"
      register: exe_result

    - name: Mostrar resultado de la ejecución del archivo .exe
      debug:
        var: exe_result