- name: Ejecutar archivos .exe
  hosts: all
  gather_facts: false
  become: yes

  vars:
    archivo_exe: 'C:\Windows\System32\ipconfig.exe'

  tasks:
    - name: Ejecutar archivo .exe
      win_shell: "{{ archivo_exe }}"
      args:
        executable: cmd
      register: salida_exe

    - name: Mostrar resultado de la ejecución del archivo .exe
      debug:
        var: salida_exe