- name: Ejecutar script de Powershell
  hosts: all
  gather_facts: false
  become: yes

  vars:
    script: 'C:\script.ps'
  tasks:
    - name: Ejecutar script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "{{ script }}"
      register: salida

    - name: Mostrar resultado de la ejecución
      debug:
        var: salida.stdout_lines