- name: Ejecutar powershell o comando
  hosts: all
  gather_facts: false
  become: yes

  vars:
    comando: 'C:\Windows\System32\ipconfig.exe'

  tasks:
    - name: Ejecutar Powershell o comando
      win_shell: "{{ comando }}"
      register: salida

    - name: Mostrar resultado de la ejecución
      debug:
        var: salida.stdout_lines