- name: Ejecutar script de Powershell para matar un proceso
  hosts: all
  gather_facts: false
  become: yes

  vars:
    process_name: "nombre_del_proceso.exe"  # Reemplazar con el nombre del proceso que se desea matar

  tasks:
    - name: Obtener el ID del proceso
      win_shell: "Get-Process -Name {{ process_name }} | Select-Object -ExpandProperty Id"
      register: process_id

    - name: Matar el proceso
      win_shell: "Stop-Process -Id {{ process_id.stdout }} -Force"
      when: process_id.stdout | int > 0