- name: Ejecutar comando para matar un proceso
  hosts: all
  gather_facts: false
  become: yes

  vars:
    process_name: "nombre_del_proceso"  # Reemplazar con el nombre del proceso que se desea matar

  tasks:
    - name: Matar el proceso
      win_shell: "taskkill /F /IM {{ process_name }} " 
      register: process_id
      ignore_errors: yes