---
- name: Listar unidades disponibles en los equipos Windows
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Obtener las unidades disponibles en el equipo
      win_shell: |
        Get-PSDrive -PSProvider FileSystem | Where-Object { $_.Free -ne $null } | Select-Object -ExpandProperty Name
      register: drives

    - name: Obtener el nombre del usuario actual
      win_shell: |
        (Get-WmiObject -Class Win32_ComputerSystem).UserName
      register: current_user

    - name: Construir datos para el archivo CSV
      set_fact:
        csv_data: |
          Nombre de Máquina,Usuario,Unidades
          {{ ansible_hostname }},{{ current_user.stdout.strip() }},{{ drives.stdout_lines | join(' ') }}

    - name: Guardar las rutas de las unidades en un archivo de texto
      win_copy:
        content: "{{ csv_data }}"
        dest: "C:\\Users\\Public\\{{ ansible_hostname }}_unidades.csv"

    - name: Mostrar hora de finalización script
      debug:
        msg: "Hora de finalización: {{ '%Y-%m-%d %H:%M:%S' | strftime }}"

