---
# copia archivos windows de un folder de la red a otro
- name: ping y copia 
  hosts: all 
  gather_facts: true
  vars:
    source: '\\yaocsrfls2.ypfb-andina.com.bo\awx\mfa\'
    destination: 'c:\temp\dest\'
    user: 'user'
    passw: '{{vault_user1}}'
  tasks:
  - name: copia archivos
    win_copy:
      src: '{{ source }}'
      dest: '{{ destination }}'
      remote_src: yes
    vars:
      ansible_become: true
      ansible_become_method: runas
      ansible_become_user: '{{ user }}'
      ansible_become_pass: '{{ passw }}'
