--- 
- name: Ver versi贸n de Sistema Operativo Windows
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Obtener versi贸n del sistema operativo
      win_shell: |
        Get-WmiObject -Class Win32_OperatingSystem |
        Select-Object CSName, Caption |
        ConvertTo-Json
      register: os_version

    - name: Mostrar resultado en formato de tabla
      debug:
        msg: |
          Nombre del Equipo | Versi贸n del Sistema Operativo
          {{ os_version.stdout | from_json | json_query('[].{Nombre: CSName, Versi贸n: Caption}') | tablesort }}

