--- 
- name: Ver versión de Sistema Operativo Windows
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Obtener versión del sistema operativo
      win_shell: |
        Get-WmiObject -Class Win32_OperatingSystem |
        Select-Object CSName, Caption |
        ConvertTo-Json
      register: os_version

    - name: Mostrar resultado en formato de tabla
      debug:
        var: item
      loop: "{{ os_version | json_query('[].{Nombre: CSName, Version: Caption}') }}"