--- 
- name: verifica si un archivo de Windows existe
  hosts: all
  gather_facts: false
  become: yes
  vars:
    archivo: "C:\\Users\\Public\\version2.txt"
    logfile: "C:\\path\\to\\your\\file.txt" 
  tasks:
    - name: Verifica si el archivo existe
      win_stat:
        path: "{{ archivo }}"
      register: file_stat

    - name: Write log if file exists
      ansible.windows.win_shell: |
        if (${{ file_stat.stat.exists }}) {{
          $LogMessage = $env:COMPUTERNAME
          $LogMessage | Out-File -FilePath "{{ logfile }}" -Append
        }}
      when: file_stat.stat.exists
