- name: Elimina Carpeta si existe
  hosts: all
  gather_facts: false
  become: yes

  vars:
    folder_name: "nombre_del_folder"  # Reemplazar con el nombre del folder para eliminar

  tasks:
    - name: Verificar si el folder existe
      win_stat:
        path: "{{ folder_name }}"
      register: folder_info

    - name: Eliminar el folder si existe
      win_file:
        path: "{{ folder_name }}"
        state: absent
      when: folder_info.stat.exists