--- 
- name: Ver un valor de registro de Windows
  hosts: all
  gather_facts: false
  become: yes
  vars:
    ruta_registro: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
    nombre_valor: 'Userinit'
  tasks:
    - name: Mostrar el valor actual del registro
      ansible.builtin.win_command: reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v "Userinit"
      register: reg_value_before

    - name: Mostrar valor actual
      debug:
        msg: "{{ reg_value_before.stdout_lines }}"
        