--- 
- name: Modificar registro de Windows
  hosts: all
  gather_facts: false
  become: yes
  vars:
    ruta_registro: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
    nombre_valor: 'Userinit'
    nuevo_valor: 'C:\Windows\system32\userinit.exe'
  tasks:
    - name: Mostrar el valor actual del registro
      ansible.builtin.win_command: reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v "Userinit"
      register: reg_value_before

    - name: Mostrar valor actual
      debug:
        msg: "{{ reg_value_before.stdout_lines }}"

    - name: Modificar valor userinit
      win_regedit:
        path: "{{ ruta_registro }}"
        name: "{{ nombre_valor }}"
        data: "{{ nuevo_valor }}"
        type: string
        state: present