--- 
- name: Ver un valor de registro de Windows
  hosts: all
  gather_facts: false
  become: yes
  vars:
    ruta_registro: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
    nombre_valor: 'Userinit'
    nuevo_valor: 'C:\Windows\system32\userinit.exe'
  tasks:
    - name: Mostrar el valor actual del registro
      ansible.builtin.win_command: reg query ""{{ ruta_registro }}"" /v "{{ nombre_valor }}"
      register: reg_value_before

    - name: Mostrar valor actual
      debug:
        msg: "{{ reg_value_before.stdout_lines }}"
        