---
- name: Bloquear usuario en un servidor Linux
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Verificar si el usuario tiene procesos en ejecución
      shell: "pgrep -u {{ user_to_block }} || true"
      register: user_processes

    - name: Mostrar mensaje si el usuario tiene procesos activos
      debug:
        msg: "El usuario {{ user_to_block }} tiene procesos activos y no será bloqueado."
      when: user_processes.stdout != ""

    - name: Bloquear la cuenta del usuario si NO tiene procesos activos
      ansible.builtin.user:
        name: "{{ user_to_block }}"
        shell: /sbin/nologin
        password_lock: true
      when: user_processes.stdout == ""

    - name: Confirmar estado del usuario
      shell: "passwd -S {{ user_to_block }}"
      register: user_status
      when: user_processes.stdout == ""

    - name: Mostrar estado del usuario bloqueado
      debug:
        msg: "Estado del usuario {{ user_to_block }}: {{ user_status.stdout }}"
      when: user_processes.stdout == ""