# crea usaurio
- name: Crear usuario de sistema operativo
  hosts: all 
  become: yes
  gather_facts: false

  vars:
    username: "usuario"
    user_password: "{{ 'secure_password' | password_hash('sha512') }}"  # Cambiar la contraseña según sea necesario
    user_shell: "/bin/bash"
    user_home: "/home/{{ username }}"

  tasks:
    - name: Crear el usuario
      user:
        name: "{{ username }}"
        password: "{{ user_password }}"
        shell: "{{ user_shell }}"
        home: "{{ user_home }}"
        state: present

    - name: Crear el directorio home si no existe
      file:
        path: "{{ user_home }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'

    - name: Agregar el usuario al grupo sudo (opcional)
      user:
        name: "{{ username }}"
        groups: "sudo"
        append: yes

    - name: Configurar mensaje de bienvenida (motd) para el usuario (opcional)
      copy:
        dest: "{{ user_home }}/welcome.txt"
        content: |
          Bienvenido, {{ username }}.
          Este es tu servidor Linux.
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'
