# crea usaurio
- name: Deshailitar servicio Linux
  hosts: all 
  become: yes
  gather_facts: false

  tasks:
    - name: Detener servicio si está activo
      ansible.builtin.systemd:
        name: "{{ servicio }}"
        state: stopped
        enabled: false