# crea usaurio
- name: Listar usuarios de sistema operativo
  hosts: all 
  become: yes
  gather_facts: false

  tasks:
      - name: Obtener usuarios con UID >= 1000 (excepto nobody)
        command: "awk -F: '$3 >= 1000 && $3 != 65534 { print $1 }' /etc/passwd"
        register: usuarios

      - name: Obtener grupos de cada usuario
        shell: "id -nG {{ item }}"
        loop: "{{ usuarios.stdout_lines }}"
        register: grupos_usuario
        loop_control:
          label: "{{ item }}"

      - name: Mostrar usuarios y sus grupos
        debug:
          msg: |
            Usuario: {{ item.item }}
            Grupos: {{ item.stdout }}
        loop: "{{ grupos_usuario.results }}"